### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [ri58-sibsutis/irregular-verbs#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:
1. В [wiki](https://github.com/ri58-sibsutis/irregular-verbs/wiki) проекта написана статья с ТЗ.
2. В [issues](https://github.com/ri58-sibsutis/irregular-verbs/issues) созданы задачи.
3. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by evgeny-p** [comment]
1. В блоке «Задачи» фактически смешаны цели проекта и функционал.
   
   Цели:
   
   > - Проверка знаний неправильных глаголов английского языка.
   > - Обучение правильному написанию глаголов.
   > - Развитие памяти, внимания.
   
   Функциональные требования:
   
   > - Разные уровни сложности.
   > - Ввод текстом/варианты ответов(номера).
   > - Подведение итогов выполнения, вывод итогов.
   > - Проверка вводимой пользователем строки, выявление количества ошибок.
   > - Сохранение результатов для отдельных пользователей.
   
   Нужно разнести на отдельные блоки.
2. > Формат входных данных
   > 1. Массив символов.
   > 2. Число.
   
   Массив чего? Какое число? По этому описанию даже сразу понятно, что речь о вводе данных в интерактивном режиме.
3. Ничего не сказано о формате хранения неправильных глаголов. В файле? В базе? Скачиваются по сети? В каком формате?
4. Заявлены различные уровни сложности, но не прописано, чем они будут отличаться.
5. Что есть «Значок приложения» в разделе «Интерфейс»?
6. «Значок паузы» — зачем? Нигде в ТЗ не было упоминания об ограничениях времени на ответы.
7. Цвет иконок на текущем этапе не имеет значения.
8. Указано, что есть главное меню с тремя кнопками. При этом нет кнопки начала теста.
9. Какую библиотеку планируется использовать для разработки интерфейса? Приложение будет графическим или консольным? Текущее описание допускает оба варианта.
10. Хромает верстка ТЗ. Заголовки оформлены как простой текст с выделением, нумерация заголовков выделена как код. Переделываем следующим образом:
    1. Убираем нумерацию заголовков.
    2. Снимаем с заголовков несемантическое выделение. В документе должно быть не более одного заголовка первого уровня. «Функционал проекта», «Формат выходных данных», «Интерфейс приложения» — заголовки второго уровня. «Задачи», «Сценарии использования» — заголовки третьего уровня.
    3. Убиарем горизонтальные линии.

**Comment by savayame** [comment]
Отредактировала. Мне не совсем понятен пункт под номером 9, и как можно его оформить в ТЗ. Не могли бы Вы пояснить?
To: @evgeny-p

**Comment by evgeny-p** [comment]
Обсудим на паре, напомните.

**Comment by evgeny-p** [comment]
Список задач переработан с учетом сроков.
